# Generated by Django 3.2.13 on 2022-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeData',
            fields=[
                ('molecule_chembl_id', models.CharField(db_column='molecule_chembl_id', max_length=255, primary_key=True, serialize=False)),
                ('smiles', models.CharField(blank=True, db_column='smiles', max_length=255, null=True)),
                ('molecule_type', models.CharField(blank=True, db_column='molecule_type', max_length=255, null=True)),
                ('alogp', models.CharField(blank=True, db_column='alogp', max_length=255, null=True)),
            ],
        ),
    ]
